# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9c15fdb9-3b5e-40ad-91ec-0891c671ac9a";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-9c15fdb9-3b5e-40ad-91ec-0891c671ac9a".device = "/dev/disk/by-uuid/9c15fdb9-3b5e-40ad-91ec-0891c671ac9a";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-9c15fdb9-3b5e-40ad-91ec-0891c671ac9a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-9c15fdb9-3b5e-40ad-91ec-0891c671ac9a";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8890-E097";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3a1e612c-ba91-4004-b579-db78e0d828b0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
